# Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from main import my_pdist, my_squareform, my_linkage

import warnings
warnings.filterwarnings('ignore')

# Data

In [3]:
data = np.array([[1,2],[9,-4],[5,6],[21,8]])

# `pdist`

In [4]:
vector1 = pdist(data, metric='euclidean')
vector2 = my_pdist(data, metric='euclidean')

In [5]:
print("{0}\n{1}".format(vector1, vector2))

[10.          5.65685425 20.88061302 10.77032961 16.97056275 16.1245155 ]
[10.          5.65685425 20.88061302 10.77032961 16.97056275 16.1245155 ]


# `squareform`

In [6]:
matrix1 = squareform(vector1)
matrix1

array([[ 0.        , 10.        ,  5.65685425, 20.88061302],
       [10.        ,  0.        , 10.77032961, 16.97056275],
       [ 5.65685425, 10.77032961,  0.        , 16.1245155 ],
       [20.88061302, 16.97056275, 16.1245155 ,  0.        ]])

In [7]:
matrix2 = my_squareform(vector1)
matrix2

array([[ 0.        , 10.        ,  5.65685425, 20.88061302],
       [10.        ,  0.        , 10.77032961, 16.97056275],
       [ 5.65685425, 10.77032961,  0.        , 16.1245155 ],
       [20.88061302, 16.97056275, 16.1245155 ,  0.        ]])

# `linkage`

In [8]:
linkage(matrix1, method='single', metric='euclidean')

array([[ 0.        ,  2.        ,  9.33883672,  2.        ],
       [ 1.        ,  4.        , 15.53821494,  3.        ],
       [ 3.        ,  5.        , 26.88968289,  4.        ]])

In [9]:
my_linkage(matrix1, method='single', metric='euclidean')

array([[ 0.        ,  2.        ,  9.33883672,  2.        ],
       [ 1.        ,  4.        , 15.53821494,  3.        ],
       [ 3.        ,  5.        , 26.88968289,  4.        ]])